name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # 두 가지 환경을 매트릭스로 정의하여 macOS와 Ubuntu에서 각각 실행
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      # 1. 리포지토리 코드 체크아웃 (v2에서 v3으로 업데이트)
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Flutter 설치
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'  # 원하는 Flutter 버전 입력

      # 3. 의존성 설치
      - name: Install dependencies
        run: flutter pub get

      # 4. Flutter 테스트 실행
      - name: Run tests
        run: flutter test

      # 5. Android 빌드 (Ubuntu에서만 실행)
      - name: Build Android APK
        if: matrix.os == 'ubuntu-latest'
        run: flutter build apk

      # 6. iOS 빌드 (macOS에서만 실행)
      - name: Build iOS app (simulator)
        if: matrix.os == 'macos-latest'
        run: flutter build ios --simulator
