name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # macOS와 Ubuntu 환경을 분리하여 설정
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      # 1. 리포지토리 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Flutter 설치
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'  # 원하는 Flutter 버전 입력

      # 3. 의존성 설치
      - name: Install dependencies
        run: flutter pub get

      # 4. Flutter 테스트 실행
      - name: Run tests
        run: flutter test

      # 5. Android 빌드 (APK)
      - name: Build Android APK
        run: flutter build apk

      # 6. iOS 빌드 (macOS에서만 실행)
      - name: Build iOS app
        if: runner.os == 'macOS'  # macOS에서만 실행
        run: flutter build ios
